config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "index", to: "pages#index"
  get "tvshows", to: "tv_shows#index"
  get "show", to: "tv_shows#show"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :tv_shows, only: [:index, :show] do
    resources :reviews, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  # GET /paintings or /paintings.json

end

app/models/director.rb
class Director < ApplicationRecord
  belongs_to :tv_show
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :tv_show
  validates :content, length: {minimum: 20}
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  attribute :image_url, :string
  attribute :director, :string
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def index
    @tv_shows = TvShow.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @tv_show = TvShow.find(params[:tv_show_id])
    @review = Review.new(review_params)
    @review.tv_show = @tv_show
    respond_to do |format|
      if @review.save
        format.html { redirect_to tv_show_path(@tv_show) }
        format.json
      else
        format.html { render "tv_shows/show", status: :unprocessable_entity }
        format.json
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController

  def index
    @tv_shows = TvShow.all
    if params[:title].present?
      @tv_shows = @tv_shows.where("title ILIKE ?", "%#{params[:title]}%")
    end
    if params[:year].present?
      @tv_shows = @tv_shows.where("year = ?", "#{params[:year]}")
    end
    if params[:genre].present?
      @tv_shows = @tv_show_params.where("genre ILIKE ?", "%#{params[:genre]}%")
    end
  end

  def show
    @tv_show = TvShow.find(params[:id])
    @review = Review.new
  end

  # GET /tv_shows/new
  def new
    @tv_show = Tvshow.new
  end
  # GET /tv_shows/1/edit
  def edit
    @tv_show = TvShow.new
  end
  # POST /tv_shows or /tv_shows.json

  def create
    @tv_show = TvShow.new(params[:tv_show])
    tv_show.save
    redirect_to tv_show_path(@tv_show)
  end

  private

  def tv_show_params
    params.require(:tv_show).permit(:title, :photo, :year, :genre, :synopsis)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvShows</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner_HP" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/don85v6ji/image/upload/v1681637596/7-13_xsf1or.jpg);">
  <div class="home_container">
    <h1>SERIES <strong></h1>
    <p>Change your life and find your favourite series!</p>
    <a class="btn btn-flat banner-btn" href="/tv_shows">Watch your favourite series now</a>
  </div>

  <div class="car container">
  <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: tv_shows_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :Title,
            params[:Title],
            class: "form-control",
            placeholder: "Title"
        %>
        <%= text_field_tag :year,
            params[:year],
            class: "form-control",
            placeholder: "Year"
        %>
        <%= text_field_tag :genre,
            params[:genre],
            class: "form-control",
            placeholder: "Genre"
        %>

      <%= submit_tag "Search", name: "", class: "btn_form btn-primary" %>
    <% end %>
  </div>
</div>
</div>
</div>
<div class="card-group">
  <div class="card">
    <img src="https://res.cloudinary.com/don85v6ji/image/upload/v1681637596/download-1_pqbxem.jpg"  class="card-img-top img-fluid" alt="...">
    <div class="card-body">
      <h5 class="card-title">Spinning Out</h5>
    </div>
  </div>
  <div class="card">
    <img src="https://res.cloudinary.com/don85v6ji/image/upload/v1681637596/download-3_azxbom.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Virgin River</h5>

    </div>
  </div>
  <div class="card">
    <img src="https://res.cloudinary.com/don85v6ji/image/upload/v1681637596/download-2_t6mslv.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Selling Sunset</h5>

    </div>
  </div>
</div>
<div class="card-group">
  <div class="card">
    <img src="https://res.cloudinary.com/don85v6ji/image/upload/v1681637596/images-2_in8l13.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">The Crown</h5>

    </div>
  </div>
  <div class="card">
    <img src="https://res.cloudinary.com/don85v6ji/image/upload/v1681637596/images-1_lm3qfi.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Drive to Survive</h5>

    </div>
  </div>
  <div class="card">
    <img src="https://res.cloudinary.com/don85v6ji/image/upload/v1681637596/7-13_xsf1or.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Peaky Blinders</h5>

    </div>
  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Crysanne?tab=repositories"><i class="fab fa-github"></i></a>
    <a href="www.linkedin.com/in/crysanne-yiannopoulos"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <a href="https://github.com/Crysanne tv_series">Crysanne Yiannopoulos</a>
  </div>
</div>

app/views/reviews/_form.html.erb
 <%= simple_form_for([tv_show, review], data: {insert_in_list_target:"form", action: "submit->insert-in-list#send"}) do |f| %>
    <%= f.input :content %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <i class="fa-solid fa-bars"></i>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class: "navbarlogo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
          <div class= "d-flex align-items-center">
          <i class="fa-solid fa-user"></i> <%= link_to "Login/Register ", new_user_session_path, class: "nav-link" %>
          </li>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tv_shows/_review.html.erb
<p><%= review.content %></p>

app/views/tv_shows/edit.html.erb
<%= render "form", tv_show: @tv_show %>

app/views/tv_shows/form.html.erb
<<%= simple_form_for(tv_show) do |f| %>
 <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :photo %>
  <%= f.input :photo, as: :file %>
   <%= form.submit %>
<% end %>

app/views/tv_shows/index.html.erb
<main class="container">
  <h1 class="my-4">ALL SERIES</h1>
  <p>All your favourite series on a single platform</p >

  <div class="row">
    <% @tv_shows.each do |tv_show| %>
      <div class="col-md-4 col-lg-3 mb-4">
        <div class="card h-100">
          <%= link_to tv_show_path(tv_show) do %>
            <%= image_tag tv_show.photo, alt:tv_show.title, class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= tv_show.title %></h5>
            <p class="card-text"><%= tv_show.year %></p >
            <p class="card-text"><%= tv_show.genre %></p >
          </div>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/tv_shows/new.html.erb
<%= render "form", tv_show: @tv_show %>

app/views/tv_shows/show.html.erb
<div class="container" data-controller="insert-in-list" data-insert-in-list-position-value="afterbegin">

  <h1><%= @tv_show.title %> </h1>

  <p><strong>Year</strong>: <%= @tv_show.year %></p>
  <p><strong>Genre</strong>: <%= @tv_show.genre %></p>
  <p><strong>Synopsis</strong>: <%= @tv_show.synopsis %></p>

  <h2><%= pluralize @tv_show.reviews.size, "review" %></h2>

  <%= render 'reviews/form', tv_show: @tv_show, review: @review %>

  <div data-insert-in-list-target="items" >
    <% if @tv_show.reviews.blank? %>
      Be the first to leave a review for <%= @tv_show.title %>
    <% else %>
      <% @tv_show.reviews.each do |review| %>
        <%= render 'tv_shows/review', review: review %>
      <% end %>
    <% end %>
  </div>



  <%= link_to "Back to all series", tv_shows_path %>
</div>